name: 'The Workshop Events & Experiences'
favicon: null
layout_spectrum: 0.47892574477009475
typography_spectrum: 0.23906548833474517
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.46683400915935636
  lightness: 0.4036083808168769
  saturation: 0.021061299834400415
  rhythmicContrast: 0.889462617225945
purpose: []
